name: envPaperScissorsRock
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - pip

  # Logging
  - loguru
  # Jupyter Notebook
  - ipykernel
  - ipywidgets
  # Natural Language processing
  - nltk
  # Data analysis
  - scikit-learn
  - wordcloud
  # Data handling
  - numpy
 

  # Pip installationen
  - pip:
    # Data handling
    - pandas
    # Data analysis
    - pandas-profiling
